"""DOCKER_ADD_HOST / BACKUP_CA_FILE helpers for Compose db and backup docker runs."""

from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Any

from catalpa_tooling.config import ProjectConfig
from catalpa_tooling.local_proxy import local_proxy_data_dir

DOCKER_ADD_HOST_ENV = "DOCKER_ADD_HOST"
BACKUP_CA_FILE_ENV = "BACKUP_CA_FILE"

# Fixed path inside containers (ro bind-mount from BACKUP_CA_FILE on the host).
BACKUP_CA_CONTAINER_PATH = "/etc/ssl/backup-ca/ca.crt"

_HOST_IP_RE = re.compile(
    r"^(?P<name>[^:\s]+):(?P<ip>(?:\d{1,3}\.){3}\d{1,3})$"
)


def parse_docker_add_hosts(env: dict[str, str]) -> list[tuple[str, str]]:
    """Parse ``DOCKER_ADD_HOST`` into ``(hostname, ipv4)`` pairs.

    Values are comma- and/or whitespace-separated ``name:ip`` entries.
    """
    raw = (env.get(DOCKER_ADD_HOST_ENV) or "").strip()
    if not raw:
        return []
    parts = re.split(r"[,\s]+", raw)
    out: list[tuple[str, str]] = []
    for part in parts:
        p = part.strip()
        if not p:
            continue
        m = _HOST_IP_RE.match(p)
        if not m:
            raise ValueError(
                f"{DOCKER_ADD_HOST_ENV} entry {p!r} must be hostname:IPv4 "
                f"(e.g. s3.backup.internal:172.16.92.28)"
            )
        out.append((m.group("name"), m.group("ip")))
    return out


def docker_add_host_args(env: dict[str, str]) -> list[str]:
    """``docker run --add-host=name:ip`` flags from ``DOCKER_ADD_HOST``."""
    args: list[str] = []
    for name, ip in parse_docker_add_hosts(env):
        args.extend(["--add-host", f"{name}:{ip}"])
    return args


def backup_ca_host_path(env: dict[str, str]) -> str | None:
    """Absolute host path to the backup CA PEM, or ``None`` if unset."""
    raw = (env.get(BACKUP_CA_FILE_ENV) or "").strip()
    if not raw:
        return None
    path = Path(raw).expanduser()
    if not path.is_absolute():
        raise ValueError(
            f"{BACKUP_CA_FILE_ENV} must be an absolute path on the deploy host, got {raw!r}"
        )
    return str(path)


def apply_inferred_backup_ca_file(
    env: dict[str, str],
    config: ProjectConfig,
    env_name: str,
) -> None:
    """If ``BACKUP_CA_FILE`` is unset and ``backup-tls.yaml`` exists, set the install path.

    Default host path: ``{ops.config_dir}/tls/backup-ca.crt``. Explicit ``BACKUP_CA_FILE`` wins.
    Mutates ``env`` in place.
    """
    if (env.get(BACKUP_CA_FILE_ENV) or "").strip():
        return
    from catalpa_tooling.backup_tls import backup_tls_path, default_backup_ca_file

    if backup_tls_path(config, env_name).is_file():
        env[BACKUP_CA_FILE_ENV] = default_backup_ca_file(config)


def docker_ca_volume_args(env: dict[str, str]) -> list[str]:
    """``-v host_ca:BACKUP_CA_CONTAINER_PATH:ro`` when ``BACKUP_CA_FILE`` is set."""
    host = backup_ca_host_path(env)
    if not host:
        return []
    return ["-v", f"{host}:{BACKUP_CA_CONTAINER_PATH}:ro"]


def docker_ca_env_flags_for_restic(env: dict[str, str]) -> list[str]:
    """``-e AWS_CA_BUNDLE=…`` when a backup CA is mounted."""
    if not backup_ca_host_path(env):
        return []
    return ["-e", f"AWS_CA_BUNDLE={BACKUP_CA_CONTAINER_PATH}"]


def docker_host_tls_override_path(config: ProjectConfig, env_name: str) -> Path:
    """Path for the ephemeral compose override (alongside local-proxy overrides)."""
    project = re.sub(r"[^a-zA-Z0-9._-]+", "-", config.meta.name.strip()) or "project"
    env = re.sub(r"[^a-zA-Z0-9._-]+", "-", env_name.strip()) or "env"
    return local_proxy_data_dir() / "overrides" / f"{project}-{env}-backup-tls.yaml"


def write_docker_host_tls_override(
    config: ProjectConfig,
    env_name: str,
    env: dict[str, str],
) -> Path | None:
    """Write compose override for ``db`` extra_hosts + CA volume; return path or ``None``."""
    try:
        hosts = parse_docker_add_hosts(env)
        ca_host = backup_ca_host_path(env)
    except ValueError:
        raise

    if not hosts and not ca_host:
        return None

    db_service = config.stack.services.db
    path = docker_host_tls_override_path(config, env_name)
    path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        f"# Generated by catalpa-workspace-tooling for dk {env_name} "
        f"(DOCKER_ADD_HOST / BACKUP_CA_FILE).",
        "services:",
        f"  {db_service}:",
    ]
    if hosts:
        lines.append("    extra_hosts:")
        for name, ip in hosts:
            lines.append(f'      - "{name}:{ip}"')
    if ca_host:
        lines.append("    volumes:")
        lines.append(f'      - "{ca_host}:{BACKUP_CA_CONTAINER_PATH}:ro"')

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path.resolve()


def docker_host_tls_extra_compose_files(
    info: dict[str, Any],
    config: ProjectConfig,
    env_name: str,
    env_add: dict[str, str],
    compose_args: list[str],
) -> list[str]:
    """Return override path when compose should inject backup TLS hosts/CA on ``db``."""
    _ = info  # reserved for future verb/env gating using info.yaml
    if not compose_args:
        return []
    verb = compose_args[0]
    # Match local-proxy verbs; also cover ``run`` / ``exec`` / ``create`` when they
    # recreate or start ``db`` with overrides (Compose merges -f on these).
    if verb not in ("up", "down", "restart", "run", "create", "start"):
        return []
    merged = {**os.environ, **env_add}
    apply_inferred_backup_ca_file(merged, config, env_name)
    override = write_docker_host_tls_override(config, env_name, merged)
    if override is None:
        return []
    return [str(override)]


def merge_extra_compose_files(*groups: list[str]) -> list[str] | None:
    """Concatenate override path lists; return ``None`` when empty."""
    out: list[str] = []
    for g in groups:
        out.extend(g)
    return out or None


def compose_dash_f_args(
    compose_file: str,
    env: dict[str, str],
    *,
    config: ProjectConfig | None = None,
    env_name: str | None = None,
    compose_verb: str = "up",
) -> list[str]:
    """Build ``-f`` args including backup-tls override when knobs are set."""
    args = ["-f", compose_file]
    if config is None or not env_name:
        return args
    try:
        extras = docker_host_tls_extra_compose_files(
            {},
            config,
            env_name,
            env,
            [compose_verb],
        )
    except ValueError:
        raise
    for path in extras:
        args.extend(["-f", path])
    return args
