"""Detect stack images left over from another branch or an older HEAD, and rebuild them.

``COMPOSE_PROJECT_NAME`` is fixed per env, but ``STACK_IMAGE_TAG`` falls through to the git
branch name (``_default_image_tag``) whenever the env pins no ``image_tag``. For unpinned envs —
``dev``, ``full`` — every ``git checkout`` therefore changes which image the stack refers to,
while the containers and local images from the previous branch stay exactly where they were.
``dk dev manage`` / ``dk full db restore`` then happily talk to last branch's stack.

The image is the source of truth: builds are stamped with ``catalpa.git_sha`` and
``catalpa.stack_image_tag``, and the check compares those labels against local git. There are no
fingerprint files and no persisted state — everything is derived from ``config`` and ``env_add``
on each run.

Tooling stamps the labels itself, through a generated label-only compose override passed as an
extra ``-f`` at build time, so projects pick this up by upgrading tooling alone rather than by
editing their own compose files.

Scope: the services in ``stack_build_services`` (db / web / proxy) — exactly the set
``_ensure_local_stack_images_built`` can rebuild. The dev-only ``node`` service is deliberately
excluded; reporting it stale would produce a rebuild path that cannot fix it. See issue #67.
"""

from __future__ import annotations

import json
import os
import sys
import tempfile
from dataclasses import dataclass

from catalpa_tooling.config import ProjectConfig
from catalpa_tooling.dk_stack import stack_build_services
from catalpa_tooling.run_cmd import run as run_cmd

LABEL_GIT_SHA = "catalpa.git_sha"
LABEL_IMAGE_TAG = "catalpa.stack_image_tag"

SKIP_ENV_VAR = "DK_SKIP_STALE_STACK"

# Metadata / host-only commands, and anything that tears the stack down or only reads it.
# `info`, `secrets`, `dc-backup` and `host` return before the deploy context loads, so they can
# never reach the hook and need no entry here.
_SKIP_ENV_COMMANDS = frozenset(
    {"docker", "zabbix", "storage", "ensure_volumes", "trust-caddy-cert"}
)
_SKIP_COMPOSE_VERBS = frozenset({"down", "ps", "logs", "config"})


@dataclass(frozen=True)
class StaleReason:
    """Why the local stack no longer matches the checkout."""

    service: str
    detail: str
    containers_running: bool

    def __str__(self) -> str:
        return f"{self.service}: {self.detail}"


def should_ensure_stack_checkout(
    env_command: str | None,
    compose_args: list[str] | None,
    *,
    use_prepulled_registry: bool,
) -> bool:
    """True when this command should verify the stack matches the checkout before running.

    Opt-out rather than an allowlist, so new subcommands are covered by default.
    """
    if use_prepulled_registry:
        return False
    if (os.environ.get(SKIP_ENV_VAR) or "").strip() == "1":
        return False
    if env_command in _SKIP_ENV_COMMANDS:
        return False
    if env_command == "wipe":
        return False
    if env_command in (None, "compose"):
        verb = (compose_args or ["up"])[0] if compose_args else "up"
        if verb in _SKIP_COMPOSE_VERBS:
            return False
    return True


def label_override_yaml(config: ProjectConfig) -> str:
    """Compose fragment stamping the catalpa labels onto every stack build service.

    Service names are per-project (``web`` is ``django`` on some stacks), so this is generated
    rather than shipped as a static asset.
    """
    lines = ["# Generated by catalpa-tooling. Not written to the repo.", "services:"]
    for service in stack_build_services(config):
        lines.extend(
            [
                f"  {service}:",
                "    build:",
                "      labels:",
                f'        {LABEL_GIT_SHA}: "${{VITE_GIT_SHA}}"',
                f'        {LABEL_IMAGE_TAG}: "${{STACK_IMAGE_TAG}}"',
            ]
        )
    return "\n".join(lines) + "\n"


def write_label_override(config: ProjectConfig) -> str:
    """Write the label override to a temp file and return its path.

    Compose resolves relative ``build.context`` against the *first* ``-f``'s directory, so this
    file living outside the repo does not disturb path resolution.
    """
    fd, path = tempfile.mkstemp(prefix="catalpa-stack-labels-", suffix=".yaml")
    with os.fdopen(fd, "w", encoding="utf-8") as fh:
        fh.write(label_override_yaml(config))
    return path


def _compose_config(
    config: ProjectConfig, compose_file: str, env_add: dict[str, str]
) -> dict:
    """Resolved compose config as JSON (same env as ``compose build``)."""
    run_env = os.environ.copy()
    run_env.update(env_add)
    proc = run_cmd(
        ["docker", "compose", "-f", compose_file, "config", "--format", "json"],
        cwd=config.repo_root,
        env=run_env,
        capture_output=True,
        text=True,
        check=False,
        print_cmd=False,
    )
    if proc.returncode != 0:
        return {}
    try:
        return json.loads(proc.stdout or "{}")
    except json.JSONDecodeError:
        return {}


def _inspect_labels(ref: str, env_add: dict[str, str], *, kind: str) -> dict[str, str] | None:
    """Labels for a local image or container, or None when it does not exist here."""
    run_env = os.environ.copy()
    run_env.update(env_add)
    proc = run_cmd(
        ["docker", kind, "inspect", ref, "--format", "{{json .Config.Labels}}"],
        env=run_env,
        capture_output=True,
        text=True,
        check=False,
        print_cmd=False,
    )
    if proc.returncode != 0:
        return None
    try:
        parsed = json.loads((proc.stdout or "").strip() or "null")
    except json.JSONDecodeError:
        return None
    if not isinstance(parsed, dict):
        return {}
    return {str(k): str(v) for k, v in parsed.items()}


def _running_container_id(
    config: ProjectConfig, compose_file: str, env_add: dict[str, str], service: str
) -> str | None:
    run_env = os.environ.copy()
    run_env.update(env_add)
    proc = run_cmd(
        ["docker", "compose", "-f", compose_file, "ps", "-q", service],
        cwd=config.repo_root,
        env=run_env,
        capture_output=True,
        text=True,
        check=False,
        print_cmd=False,
    )
    if proc.returncode != 0:
        return None
    first = (proc.stdout or "").strip().splitlines()
    return first[0].strip() if first and first[0].strip() else None


def _mismatch(labels: dict[str, str], *, tag: str, sha: str) -> str | None:
    """Describe how these labels differ from the checkout, or None when they match."""
    got_sha = (labels.get(LABEL_GIT_SHA) or "").strip()
    got_tag = (labels.get(LABEL_IMAGE_TAG) or "").strip()
    if not got_sha or not got_tag:
        return "image carries no catalpa.* build labels (built before this check existed, or built outside dk)"
    if got_tag != tag:
        return f"image was built for tag {got_tag!r}, checkout resolves to {tag!r}"
    if got_sha != sha:
        return f"image was built from {got_sha}, HEAD is {sha}"
    return None


def stack_images_match_checkout(
    config: ProjectConfig,
    compose_file: str,
    env_add: dict[str, str],
) -> StaleReason | None:
    """Return why the stack is stale, or None when it matches the current checkout."""
    tag = (env_add.get("STACK_IMAGE_TAG") or "").strip()
    sha = (env_add.get("VITE_GIT_SHA") or "").strip()
    if not tag or not sha:
        # Without both expected values there is nothing to compare against; declaring everything
        # stale on a failed `git rev-parse` would rebuild on every command.
        return None

    resolved = _compose_config(config, compose_file, env_add)
    services = resolved.get("services") or {}

    for service in stack_build_services(config):
        spec = services.get(service)
        if not isinstance(spec, dict) or not spec.get("build"):
            # An image-only service can never carry the labels; treating it as stale would
            # rebuild on every single command forever.
            continue

        container = _running_container_id(config, compose_file, env_add, service)
        if container:
            labels = _inspect_labels(container, env_add, kind="container")
            if labels is not None:
                detail = _mismatch(labels, tag=tag, sha=sha)
                if detail:
                    return StaleReason(service, detail, containers_running=True)
                continue

        image_ref = str(spec.get("image") or "").strip()
        if not image_ref:
            continue
        labels = _inspect_labels(image_ref, env_add, kind="image")
        if labels is None:
            # No container and no local image for the expected tag. "Nothing to compare
            # against" means build — this is the case that produced `manifest unknown`
            # from `dk dev db restore` with the stack down.
            return StaleReason(
                service,
                f"no running container and no local image {image_ref!r}",
                containers_running=False,
            )
        detail = _mismatch(labels, tag=tag, sha=sha)
        if detail:
            return StaleReason(service, detail, containers_running=False)

    return None


def ensure_stack_matches_checkout(
    config: ProjectConfig,
    compose_file: str,
    env_add: dict[str, str],
    *,
    use_prepulled_registry: bool,
    dry_run: bool = False,
    recreate: bool = True,
) -> tuple[int, StaleReason | None]:
    """Rebuild stack images when they no longer match the checkout.

    Returns ``(returncode, reason)``; a non-zero return aborts the original command. ``recreate``
    is False when the caller runs its own ``compose up`` straight afterwards, so the containers
    are not recreated twice.
    """
    from catalpa_tooling.compose import _compose
    from catalpa_tooling.remote_deploy import _ensure_local_stack_images_built

    reason = stack_images_match_checkout(config, compose_file, env_add)
    if reason is None:
        return 0, None

    print(f"Stale local stack — {reason}", file=sys.stderr)

    if dry_run:
        # A central hook that can burn fifteen minutes on a dry run is a different
        # proposition from the build guards this sits alongside.
        print(
            f"dry-run: would rebuild stack images (set {SKIP_ENV_VAR}=1 to skip this check).",
            file=sys.stderr,
        )
        return 0, reason

    print("Rebuilding stack images to match the checkout …", file=sys.stderr)
    rc = _ensure_local_stack_images_built(
        config, env_add, use_prepulled_registry=use_prepulled_registry
    )
    if rc != 0:
        return rc, reason

    if reason.containers_running and recreate:
        print("Recreating running containers …", file=sys.stderr)
        rc = _compose(
            compose_file, "up", "-d", "--build", check=False, env_add=env_add
        ).returncode
        return rc, reason
    return 0, reason


def drop_no_build_when_stale(compose_args: list[str]) -> list[str]:
    """Remove ``--no-build`` from an ``up`` that would otherwise reuse a stale image."""
    if not compose_args or compose_args[0] != "up" or "--no-build" not in compose_args:
        return compose_args
    print(
        "Stale stack: ignoring --no-build so the images can be rebuilt "
        f"(set {SKIP_ENV_VAR}=1 to keep it).",
        file=sys.stderr,
    )
    return [a for a in compose_args if a != "--no-build"]
